# Generated by Django 3.0.8 on 2020-07-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200724_0214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='dudate',
            new_name='duedate',
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('success', 'normal'), ('info', 'low')], max_length=50),
        ),
    ]
