# Generated by Django 3.0.8 on 2020-07-24 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200724_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='priority',
            new_name='priority_color',
        ),
    ]
