# Generated by Django 3.0.8 on 2020-07-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todomodel_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='priority_color',
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('danger', 'high'), ('success', 'normal'), ('info', 'low')], max_length=50),
        ),
    ]
